apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverless-router
  template:
    metadata:
      labels:
        app: serverless-router
    spec:
      containers:
        - name: serverless-router
          image: serverless_router:latest
          imagePullPolicy: Never
          
---

kind: Service
apiVersion: v1
metadata:
  name: serverless-router
spec:
  selector:
    app: serverless-router
  ports:
    - port: 4000 # Default port for image
  #type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: serverless-router
            port:
              number: 4000